<?php
 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
 
require 'vendor/autoload.php';
 
$mail = new PHPMailer(true);
 
try {
    $mail->SMTPDebug = 4;                                      
    $mail->isSMTP();                                           
    $mail->Host       = 'smtp.gmail.com;';                   
    $mail->SMTPAuth   = true;                            
    $mail->Username   = 'ashwinkv.akv@gmail.com';                
    $mail->Password   = 'ibsuesmqlugpsnil';                       
    $mail->SMTPSecure = 'ssl';                             
    $mail->Port       = 465; 
 
    $mail->setFrom('ashwinkv.akv@gmail.com', 'Name');          
    $mail->addAddress('sharanperla1234@gmail.com');
      
    $mail->isHTML(false);                                 
    $mail->Subject = 'Subject';
    $mail->Body    = 'THIS IS GENERATED BY EATABLES <b>bold</b> ';
    $mail->AltBody = 'Body in plain text for non-HTML mail clients';
    $mail->send();
    echo "Mail has been sent successfully!";
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
 
?>